application: myblog
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /styles
  static_dir: styles

- url: /.*
  script: views.application


libraries:
- name: jinja2
  version: latest